FROM nvidia/cuda:8.0-cudnn5-devel
MAINTAINER Simon C. Smith <artificialsimon@ed.ac.uk>

RUN apt-get update && apt-get install -y --no-install-recommends \
	python3.5 \
	python3-pip \
	python3-setuptools \
	git \
	vim 
RUN pip3 install --upgrade pip
RUN pip3 install tensorflow-gpu==1.0 numpy==1.15 
RUN ln -s /usr/bin/python3 /usr/bin/python 
ENV PYTHONPATH=/cogle/gym-apl/
WORKDIR "/"
RUN mkdir /cogle
WORKDIR /cogle
RUN git clone -b apl_navigation https://github.com/artificialsimon/GA3C.git
RUN git clone https://github.com/artificialsimon/gym-apl.git
RUN git clone https://github.com/openai/gym.git
WORKDIR "/cogle/gym"
RUN pip3 install .
WORKDIR "/cogle/gym-apl"
RUN pip3 install -e .
WORKDIR "/cogle/GA3C/ga3c/"
RUN mkdir checkpoints

#CMD tail -f /dev/null
#ENTRYPOINT ["/bin/bash"]
